version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: postgres_container
    volumes:
      - .:/data/postgres
    environment:
      - POSTGRES_USER=${APP_DB_USER}
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD}
      - POSTGRES_DB=${APP_DB_NAME}
    ports:
      - '${APP_DB_PORT}:${APP_DB_PORT}'
  web:
    build: .
    restart: always
    container_name: api_container
    volumes:
      - ./app:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - postgres